site_name: Agglayer Documentation
site_author: Polygon Labs
copyright: Copyright &copy; PT Services DMCC 2025
repo_name: Agglayer Documentation
repo_url: https://github.com/agglayer/agglayer-docs
edit_uri: edit/main/docs/
site_url: https://agglayer.dev/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: "#FF8E08"  
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: "#FF8E08" 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  language: en
  custom_dir: overrides
  favicon: img/favicon.ico
  logo: img/agglayer/agglayer-logo-mark-black-rgb.svg
  icon:
    logo: logo
    repo: repo
  features:
    - search.suggest
    - search.highlight
    - search.share
    #- navigation.instant #
    #- navigation.instant.progress
    - navigation.tracking
    - navigation.integration
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.sections
    - navigation.path
    - navigation.top
    - navigation.footer
    - toc.follow
    - content.code.copy
    - content.action.edit
    - navigation.indexes

nav:
  - Agglayer: 
      - Overview: index.md
      - Get Started:
        - agglayer/get-started/index.md
        - Quickstart: agglayer/get-started/quickstart.md
        - Supported Networks: https://build.agglayer.dev/chains
        - Agglayer Developer Portal: https://build.agglayer.dev
      - Core Concepts:
        - agglayer/core-concepts/index.md
        - What is Agglayer?: agglayer/core-concepts/what-is-agglayer.md
        - Architecture: agglayer/core-concepts/architecture.md
      #   - Unified Bridge: 
      #     - agglayer/core-concepts/unified-bridge.md
      #     - Core Concepts:
      #       - Data Structures: agglayer/core-concepts/unified-bridge/data-structures.md
      #       - Local Exit Root & Local Index: agglayer/core-concepts/unified-bridge/local-exit-root.md
      #       - Rollup Exit Root: agglayer/core-concepts/unified-bridge/rollup-exit-root.md
      #       - Mainnet Exit Root: agglayer/core-concepts/unified-bridge/mainnet-exit-root.md
      #       - Global Exit Root: agglayer/core-concepts/unified-bridge/global-exit-root.md
      #       - L1 Info Tree: agglayer/core-concepts/unified-bridge/l1-info-tree.md
      #     - Components & Operations:
      #       - Bridge Components: agglayer/core-concepts/unified-bridge/bridge-components.md
      #       - Asset Bridging: agglayer/core-concepts/unified-bridge/asset-bridging.md
      #       - Message Bridging: agglayer/core-concepts/unified-bridge/message-bridging.md
      #       - Bridge-and-Call: agglayer/core-concepts/unified-bridge/bridge-and-call.md
      #     - Security & Development:
      #       - Security Model: agglayer/core-concepts/unified-bridge/security-model.md
      #       - Developer Examples: agglayer/core-concepts/unified-bridge/developer-examples.md
      #   - Pessimistic Proofs: 
      #     - agglayer/core-concepts/pessimistic-proofs.md
      #     - Architecture & Data:
      #       - Architecture Overview: agglayer/core-concepts/pessimistic-proofs/architecture.md
      #       - Data Structures: agglayer/core-concepts/pessimistic-proofs/data-structures.md
      #       - Local Balance Tree: agglayer/core-concepts/pessimistic-proofs/local-balance-tree.md
      #       - Nullifier Tree: agglayer/core-concepts/pessimistic-proofs/nullifier-tree.md
      #     - Proof Components:
      #       - Bridge Exits: agglayer/core-concepts/pessimistic-proofs/bridge-exits.md
      #       - Imported Bridge Exits: agglayer/core-concepts/pessimistic-proofs/imported-bridge-exits.md
      #       - Multi Batch Header: agglayer/core-concepts/pessimistic-proofs/multi-batch-header.md
      #       - Proof Generation: agglayer/core-concepts/pessimistic-proofs/proof-generation.md
      #     - zkVM Integration:
      #       - zkVM Integration: agglayer/core-concepts/pessimistic-proofs/zkvm-integration.md
      #       - SP1 Prover Network: agglayer/core-concepts/pessimistic-proofs/sp1-prover-network.md
      #       - RiscZero Integration: agglayer/core-concepts/pessimistic-proofs/risczero-integration.md
      #       - Pico Integration: agglayer/core-concepts/pessimistic-proofs/pico-integration.md
      #     - Performance & Benchmarks:
      #       - Performance Benchmarks: agglayer/core-concepts/pessimistic-proofs/performance-benchmarks.md
      #   - State Transition Proofs: 
      #     - agglayer/core-concepts/state-transition-proofs.md
      #     - Background & Overview:
      #       - Background & Problem Statement: agglayer/core-concepts/state-transition-proofs/background.md
      #       - Trust Flow: agglayer/core-concepts/state-transition-proofs/trust-flow.md
      #     - Proof Types:
      #       - Aggchain Proof: agglayer/core-concepts/state-transition-proofs/aggchain-proof.md
      #       - ECDSA Verification: agglayer/core-concepts/state-transition-proofs/ecdsa-verification.md
      #       - Validity Proof Verification: agglayer/core-concepts/state-transition-proofs/validity-proof-verification.md
      #   - AggKit:
      #     - agglayer/core-concepts/aggkit/index.md
      #     - AggSender: agglayer/core-concepts/aggkit/aggsender.md
      #     - AggOracle: agglayer/core-concepts/aggkit/aggoracle.md
      #     - Bridge Service: agglayer/core-concepts/aggkit/bridge-service.md
      #     - L1InfoTreeSync: agglayer/core-concepts/aggkit/l1infotreesync.md
      #     - ClaimSponsor: agglayer/core-concepts/aggkit/claimsponsor.md
      #   - Prover:
      #     - agglayer/core-concepts/prover/index.md
      #     - Prover Architecture: agglayer/core-concepts/prover/architecture.md
      #     - Proof Generation: agglayer/core-concepts/prover/proof-generation.md
      #     - Verification Process: agglayer/core-concepts/prover/verification-process.md
      # - Bridge on Agglayer:
      #   - agglayer/bridging/index.md
      #   - Asset Bridging: agglayer/bridging/asset-bridging.md
      #   - Message Bridging: agglayer/bridging/message-bridging.md
      #   - Bridge-and-Call: agglayer/bridging/bridge-and-call.md
      #   - Bridge on Agglayer via VaultBridge: agglayer/bridging/vaultbridge.md
      # - Developer Tools:
      #   - agglayer/developer-tools/index.md
      #   - Agglayer SDK: agglayer/developer-tools/agglayer-sdk.md
      #   - AggSandbox:
      #     - agglayer/developer-tools/aggsandbox/index.md
      #     - Installation: agglayer/developer-tools/aggsandbox/installation.md
      #     - CLI Commands: agglayer/developer-tools/aggsandbox/cli-commands.md
      #     - Local Development: agglayer/developer-tools/aggsandbox/local-development.md
      #     - Forking from Mainnet: agglayer/developer-tools/aggsandbox/forking.md
      #   - Lxly.js:
      #     - agglayer/developer-tools/lxlyjs/index.md
      #     - Installation: agglayer/developer-tools/lxlyjs/installation.md
      #     - Client Initialization: agglayer/developer-tools/lxlyjs/client-initialization.md
      #     - ERC20 Token Operations: agglayer/developer-tools/lxlyjs/erc20-operations.md
      #     - Custom Contracts: agglayer/developer-tools/lxlyjs/custom-contracts.md
      #     - API Reference: agglayer/developer-tools/lxlyjs/api-reference.md
      #   - Bridge Service API:
      #     - agglayer/developer-tools/bridge-service-api/index.md
      #     - REST API: agglayer/developer-tools/bridge-service-api/rest-api.md
      #     - gRPC API: agglayer/developer-tools/bridge-service-api/grpc-api.md
      #     - WebSocket API: agglayer/developer-tools/bridge-service-api/websocket-api.md
      #     - Authentication: agglayer/developer-tools/bridge-service-api/authentication.md
  - CDK:
      - CDK: cdk/index.md
      - Get Started:
        - What is CDK?: cdk/get-started/overview.md
        - Why choose CDK?: cdk/get-started/benefits.md
      - cdk-opgeth:
          - Deploy a local testnet: cdk/cdk-opgeth/local-guide.md
          - Deploy a devnet: cdk/cdk-opgeth/devnet-deployment-guide.md
          - Deploy balance scanner: cdk/cdk-opgeth/balance-scanner.md
          - Architecture: cdk/cdk-opgeth/architecture.md
      - cdk-erigon:
          - Deploy a local testnet: cdk/cdk-erigon/local-deployment.md
          - Create a native token: cdk/cdk-erigon/use-native-token.md
          - Deploy balance scanner: cdk/cdk-erigon/balance-scanner.md
          - Architecture: cdk/cdk-erigon/architecture.md
          - Migration Guides:
              - General Guide: cdk/cdk-erigon/migrate/fork.md
              - Fork ID 9 to 12: cdk/cdk-erigon/migrate/forkid-9-12.md
              - Fork ID 7 to 9: cdk/cdk-erigon/migrate/forkid-7-to-9.md
      - Additional Resources:
          - Glossary: cdk/additional-resources/glossary.md
          - FAQs: cdk/additional-resources/faqs.md
  - Vault Bridge:
    - Get Started:
      - Overview: vault-bridge/get-started/overview.md
      - Architecture & Roadmap: vault-bridge/get-started/architecture.md
      - FAQ: vault-bridge/get-started/faq.md
    - Deploy:
      - Launch Checklist: vault-bridge/deploy/launch-checklist.md
    - Reference:
      - Assets & Live Vaults: vault-bridge/reference/assets-live-vaults.md
      - Risk & Security: vault-bridge/reference/risk-security.md
      - Technical Reference: "https://agglayer.github.io/vault-bridge/"

extra:
  generator: false
  analytics:
    provider: google
    property: G-PM6L5JWEZP    
  social:
    - icon: fontawesome/solid/circle-question
      link: https://support.polygon.technology/support/solutions
    - icon: fontawesome/solid/globe
      link: https://agglayer.dev/
    - icon: fontawesome/brands/github
      link: https://github.com/agglayer/agglayer-docs
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

extra_css:
  - _site_essentials/stylesheets/extra.css
  - https://fonts.googleapis.com/icon?family=Material+Icons
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

markdown_extensions:
  - toc:
      permalink: true
      permalink_title: Link to this section
      toc_depth: 4
  - codehilite
  - markdown_include.include:
      base_path: docs
  - admonition
  - footnotes
  - def_list
  - attr_list
  #- md_in_html
  - abbr
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.caret
  - meta
  - smarty
  - pymdownx.extra:
      pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - multirepo:
      cleanup: true
      keep_docs_dir: false
  - search
  - open-in-new-tab
  - redirects:
      redirect_maps:
        'docs/develop/network-details/network.md': 'cdk/index.md'
        'cdk/getting-started/index.md': 'cdk/getting-started/local-deployment.md'      
        'zkEVM/how-to/index.md': 'zkEVM/get-started/index.md'
        'cdk/concepts/index.md': 'cdk/concepts/layer2s.md'
        'tools/matic-js/installation.md': 'tools/matic-js/get-started.md'
        'pos/how-to/access-node.md': 'tools/dApp-development/tutorials/access-node.md'
        'pos/how-to/full-node/full-node-system-requirements.md': 'pos/how-to/prerequisites.md'
        'pos/how-to/validator/prerequisites.md': 'pos/how-to/prerequisites.md'
        'pos/how-to/validator/validator-system-requirements.md': 'pos/how-to/prerequisites.md'
        'pos/how-to/choose-node-type.md': 'pos/how-to/prerequisites.md'
        'pos/how-to/operate-validator-node/validator-best-practices.md': 'pos/how-to/validator/validator-best-practices.md'
        'pos/how-to/operate-validator-node/validator-commission-operations.md': 'pos/how-to/operate-validator-node/next-steps.md'
        'pos/how-to/operate-validator-node/validator-staking-operations.md': 'pos/how-to/operate-validator-node/next-steps.md'
        'pos/how-to/operating/validator-node/index.md': 'pos/how-to/operate-validator-node/next-steps.md'
        'cdk/version-matrix/index.md': 'index.md'
        'agglayer/core-concepts/Agglayer v0.3.0-Core-Features.md': 'agglayer/core-concepts/index.md'
        'agglayer/core-concepts/v0.3.md': 'agglayer/core-concepts/index.md'
        'agglayer/core-concepts/migration_guide.md': 'agglayer/core-concepts/index.md'
        'agglayer/core-concepts/ECDSA-vs-FEP.md': 'agglayer/core-concepts/index.md'
        'agglayer/core-concepts/v0.2_vs_v0.3.md': 'agglayer/core-concepts/index.md'

validation:
  absolute_links: warn
  anchors: warn

extra_javascript:
  - _site_essentials/js/mathjax.js
  - https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?version=4.8.0
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
