name: Deploy docker image to GCP
on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  docker-release:
    uses: 0xPolygon/pipelines/.github/workflows/gcp_pipeline_release_image.yaml@main
    with:
      image_name: agglayer-docs
